# Generated by Django 3.2 on 2021-07-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgHaccounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orghuser',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orghuser',
            name='staff',
            field=models.BooleanField(default=False),
        ),
    ]
