# Generated by Django 3.2 on 2021-07-27 17:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgHaccounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='user_likes',
            field=models.ManyToManyField(related_name='liked_newsposts', to=settings.AUTH_USER_MODEL),
        ),
    ]
