# Generated by Django 3.2.5 on 2021-10-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgHaccounts', '0002_newspost_user_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='orghuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images'),
        ),
    ]
