# Generated by Django 3.2 on 2021-07-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgHaccounts', '0003_fileupload_screenanswer_vaccineresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='orghuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='orghuser',
            name='last_login',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
