# Generated by Django 3.2.5 on 2021-10-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgHaccounts', '0003_orghuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orghuser',
            name='avatar',
            field=models.ImageField(blank=True, default='profile_images/default.jpg', null=True, upload_to='profile_images'),
        ),
    ]
