# Generated by Django 3.2 on 2021-07-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgHaccounts', '0004_auto_20210711_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='orghuser',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='profile picture'),
        ),
    ]
