# Generated by Django 3.2 on 2021-07-17 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgHaccounts', '0005_orghuser_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orghuser',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='profile picture'),
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.CharField(max_length=255)),
                ('newscover', models.ImageField(upload_to='news_images/')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('likes', models.PositiveIntegerField(default=0)),
                ('postContent', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_newsposts', to=settings.AUTH_USER_MODEL)),
                ('user_likes', models.ManyToManyField(related_name='liked_newsposts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alreadyLiked', models.BooleanField(default=False)),
                ('newsPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='orgHaccounts.newspost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsPost_comment', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('newsPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='orgHaccounts.newspost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
