# Generated by Django 3.2 on 2021-07-18 05:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orgHaccounts', '0006_auto_20210716_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orghuser',
            name='cover',
        ),
        migrations.AddField(
            model_name='vaccineresponse',
            name='date_received',
            field=models.DateField(default=datetime.datetime(2021, 7, 18, 5, 18, 32, 375789, tzinfo=utc), verbose_name='Vaccination date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_newsposts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='screenanswer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screenAnswers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vaccineresponse',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccineResponses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='profile picture')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
