# Generated by Django 3.2 on 2021-07-18 08:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orgHaccounts', '0007_auto_20210717_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileimage',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profileimage',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 7, 18, 8, 52, 20, 363601, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
